
# utils/exceptions.py
class CustomerNotFoundException(Exception):
    pass